-- FIXME: in real life, use a user and schema management tool
CREATE USER el WITH LOGIN PASSWORD 'abc132dev';
CREATE DATABASE whc OWNER el;

\c whc

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO el;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO el;

